import json

def format_retrieved_documents(context):
    query = context["query"]
    docs = context["documents"]
    print("---------------------------------------- FRD\n\n")

    for doc in docs:
        print(doc.metadata)
        print()
    

    formattedDocs = []
    strResult = ""
    for index, doc in enumerate(docs):
        # if index == 0:
        #     print(doc.page_content)
        #     print("\n")
        #     print(doc)
        #     print(doc.metadata)
        formattedDocs.append({
            f"[doc{index}]": {
                "content": json.dumps(doc.metadata)
            }
        })

    print("\n---------------------------------------- FRD")
    
    strResult = json.dumps(formattedDocs)
    
    if strResult == "":
        return json.dumps({"retrieved_documents": []})
    return strResult

def format_reply(reply):
    
    print("---------- am ajuns in FR")
    # print(reply["reply"])
    
    return reply["reply"]

def format_chat_history(chat_history):
    # def estimate_tokens(text: str) -> int:
    #     return (len(text) + 2) / 3
    # maxTokens = 10000
    
    buffer = ""
    for dialogue_turn in list(reversed(chat_history)):
        human = "Human: " + dialogue_turn[0]
        ai = "Assistant: " + dialogue_turn[1]#.split("\nRetrieved documents:\n[doc0]:")[0]
        buffer = "\n" + "\n".join([human, ai]) + buffer

        # if (estimate_tokens(buffer) > maxTokens):
        #   break
    return buffer

def format_product_output(product):
    """
    Formats the product details into a structured string with a red title link
    and bullet points for the description.

    Parameters
    ----------
    product : dict
        A dictionary representing a product with keys: title, price, description, and link.

    Returns
    -------
    str
        A formatted string containing the product title (as a hyperlink), price, 
        and description as a bullet list.
    """
    title = product.get("title", "Title not available")
    price = product.get("price", "Price not available")
    description = product.get("description", "Description not available")
    link = product.get("link", "#")

    # Split the description into bullet points
    bullet_points = [sentence.strip() + '.' for sentence in description.split('.') if sentence]

    # Format the output using Markdown for styling and bullet points
    formatted_output = f"**Product Title:** [{title}]({link})  \n"
    formatted_output += f"**Price:** {price}  \n\n"
    formatted_output += "**Description:**  \n"

    # Add bullet points to the formatted output
    for point in bullet_points:
        formatted_output += f"- {point}\n"
    
    return formatted_output

def ex_retrieved_documents1(docs: list = []) -> str:
    ex_retrieved_documents = """
{'title': 'Surub pentru tigla metalica, autoforant, zincat, 4.8 x 35 mm, 250 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-tigla-metalica-autoforant-zincat-4-8-x-35-mm-250-bucati/p/6027938', 'image': 'https://cdn.dedeman.ro/media/catalog/product/6/0/6027938_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '47.60 lei', 'description': 'Suruburile zincate cu saiba de otel cu cauciuc se utilizeaza la fixarea metalului pe suport de lemn si asigura o perforare usoara si o prindere rezistenta.\nSuprafata galvanizata a suruburilor asigura protectie si rezistenta ridicata la intemperii, oferind si rezistenta la coroziune. Saiba din otel cu cauciuc asigura o etanseitate perfecta, nu permite apei sa patrunda prin gaura de perforare si reprezinta o dubla protectie impotriva coroziunii.\nUtilizarea acestui produs aduce dupa sine avantaje:\nstratul de protectie antirugina si protectia UV asigura rezistenta sporita in timpul instalarii si utilizarii;\ntratamentele aplicate in procesul de productie cresc rezistenta produsului.\n  Suruburile sunt in numar de 250 in cutie, iar dimensiunile fiecaruia sunt 4.8 x 35 mm.', 'technical_specs': {'Mod de ambalare': '250 bucati', 'Lungime (mm)': '35', 'Diametru (mm)': '4.8', 'Model': 'autoforant', 'Utilizare': 'Fixare metal pe suport din lemn', 'Culoare': 'zinc', 'Finisaj': 'zincat', 'Diametru cap (mm)': '8', 'Capacitate perforare (mm)': '1.25', 'Alte caracteristici': 'Strat de protectie antirugina; protectie UV'}, '_id': '1c39ea48-d439-4f88-9f86-3df839722677', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX20, autofiletant, din otel, zincat alb, 4 x 60 mm, 200 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx20-autofiletant-din-otel-zincat-alb-4-x-60-mm-200-bucati/p/1058468', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058468_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '40.52 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX20, diametrul de 4 mm si  lungimea de 60 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 200 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '60', 'Diametru (mm)': '4', 'Diametru cap (mm)': '7.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX20', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '72aaeff6-f743-47d5-87f7-4eeea8a9f288', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 5 x 70 mm, 200 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-5-x-70-mm-200-bucati/p/1058481', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058481_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '70.61 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 5 mm si  lungimea de 70 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 200 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '70', 'Diametru (mm)': '5', 'Diametru cap (mm)': '9.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': 'c884fdce-38b7-4ea7-8920-6f4cfd6fc9f8', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 5 x 80 mm, 200 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-5-x-80-mm-200-bucati/p/1058482', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058482_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '87.33 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 5 mm si  lungimea de 80 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 200 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '80', 'Diametru (mm)': '5', 'Diametru cap (mm)': '9.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '13b4d219-d291-4a36-8bc5-64c242da6711', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX20, autofiletant, din otel, zincat alb, 4 x 35/20 mm, 500 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx20-autofiletant-din-otel-zincat-alb-4-x-35/20-mm-500-bucati/p/1058464', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058464_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '63.88 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX20, diametrul de 4 mm si  lungimea de 35 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 500 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '35', 'Diametru (mm)': '4', 'Diametru cap (mm)': '7.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX20', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '94603ec6-f2bb-4d2a-9e26-02c0e1d6112f', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 4.5 x 70 mm, 200 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-4-5-x-70-mm-200-bucati/p/1058475', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058475_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '63.18 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 4.5 mm si  lungimea de 70 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 200 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '70', 'Diametru (mm)': '4.5', 'Diametru cap (mm)': '8.8', 'Inaltime cap (mm)': '2.8', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '0c08a9c6-65e1-4243-a6fa-c739416eba39', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX20, autofiletant, din otel, zincat alb, 4 x 40/25 mm, 500 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx20-autofiletant-din-otel-zincat-alb-4-x-40/25-mm-500-bucati/p/1058465', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058465.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '74.57 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX20, diametrul de 4 mm si  lungimea de 40 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 500 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '40', 'Diametru (mm)': '4', 'Diametru cap (mm)': '7.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX20', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': 'e9b30137-b14e-4f70-9a53-d230c196e0cc', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 5 x 100 mm, 100 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-5-x-100-mm-100-bucati/p/1058484', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058484_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '59.69 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 5 mm si  lungimea de 100 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 100 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '100', 'Diametru (mm)': '5', 'Diametru cap (mm)': '9.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '3271faba-c3dd-439d-a94a-4663debdd9ae', '_collection_name': 'dedeman-screws-collection4'}
{'title': 'Surub pentru tigla metalica, autoforant, Bilka, maro inchis RAL 8019, 4.8 x 70 mm, 100 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-tigla-metalica-autoforant-bilka-maro-inchis-ral-8019-4-8-x-70-mm-100-bucati/p/6040421', 'image': 'https://cdn.dedeman.ro/media/catalog/product/6/0/6040421_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '61.02 lei', 'description': 'Suruburile cu saiba de otel cu cauciuc se utilizeaza la fixarea metalului pe suport de lemn si asigura o perforare usoara si o prindere rezistenta.\nSuprafata galvanizata a suruburilor asigura protectie si rezistenta ridicata la intemperii, oferind si rezistenta la coroziune. Saiba din otel cu cauciuc asigura o etanseitate perfecta, nu permite apei sa patrunda prin gaura de perforare si reprezinta o dubla protectie impotriva coroziunii. Stratul de vopsea este rezistent la UV si asigura mentinerea culorii timp indelungat.\nUtilizarea acestui produs aduce dupa sine avantaje:\nstratul de protectie antirugina si protectia UV asigura rezistenta sporita in timpul instalarii si utilizarii;\ntratamentele aplicate in procesul de productie cresc rezistenta produsului la coroziune si permit mentinerea culorii in timp.\n  Suruburile sunt in numar de 250 in cutie, au culoarea maro inchis (RAL 8019), iar dimensiunile fiecaruia sunt 4.8 x 70 mm.', 'technical_specs': {'Brand': 'Bilka', 'Mod de ambalare': '100 bucati', 'Lungime (mm)': '70', 'Diametru (mm)': '4.8', 'Model': 'autoforant', 'Utilizare': 'fixare metal pe suport din lemn', 'Culoare': 'maro inchis RAL 8019', 'Finisaj': 'lucios', 'Diametru cap (mm)': '8', 'Capacitate perforare (mm)': '1.25', 'Alte caracteristici': 'strat de protectie antirugina; protectie UV'}, '_id': '35cdf696-2d86-46f5-9f78-4bef7728f940', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 5 x 50/27 mm, 250 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-5-x-50/27-mm-250-bucati/p/1058479', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058479_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '64.47 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 5 mm si  lungimea de 50 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 250 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '50', 'Diametru (mm)': '5', 'Diametru cap (mm)': '9.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '0cee3354-b78e-40ea-b769-0f6de2036b44', '_collection_name': 'dedeman-screws-collection4'}
"""

def ex_retrieved_documents2(docs: list = []) -> str:
    ex_retrieved_documents = """
{'title': 'Surub pentru tigla metalica, autoforant, zincat, 4.8 x 35 mm, 250 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-tigla-metalica-autoforant-zincat-4-8-x-35-mm-250-bucati/p/6027938', 'image': 'https://cdn.dedeman.ro/media/catalog/product/6/0/6027938_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '47.60 lei', 'description': 'Suruburile zincate cu saiba de otel cu cauciuc se utilizeaza la fixarea metalului pe suport de lemn si asigura o perforare usoara si o prindere rezistenta.\nSuprafata galvanizata a suruburilor asigura protectie si rezistenta ridicata la intemperii, oferind si rezistenta la coroziune. Saiba din otel cu cauciuc asigura o etanseitate perfecta, nu permite apei sa patrunda prin gaura de perforare si reprezinta o dubla protectie impotriva coroziunii.\nUtilizarea acestui produs aduce dupa sine avantaje:\nstratul de protectie antirugina si protectia UV asigura rezistenta sporita in timpul instalarii si utilizarii;\ntratamentele aplicate in procesul de productie cresc rezistenta produsului.\n  Suruburile sunt in numar de 250 in cutie, iar dimensiunile fiecaruia sunt 4.8 x 35 mm.', 'technical_specs': {'Mod de ambalare': '250 bucati', 'Lungime (mm)': '35', 'Diametru (mm)': '4.8', 'Model': 'autoforant', 'Utilizare': 'Fixare metal pe suport din lemn', 'Culoare': 'zinc', 'Finisaj': 'zincat', 'Diametru cap (mm)': '8', 'Capacitate perforare (mm)': '1.25', 'Alte caracteristici': 'Strat de protectie antirugina; protectie UV'}, '_id': '1c39ea48-d439-4f88-9f86-3df839722677', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX20, autofiletant, din otel, zincat alb, 4 x 60 mm, 200 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx20-autofiletant-din-otel-zincat-alb-4-x-60-mm-200-bucati/p/1058468', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058468_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '40.52 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX20, diametrul de 4 mm si  lungimea de 60 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 200 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '60', 'Diametru (mm)': '4', 'Diametru cap (mm)': '7.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX20', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '72aaeff6-f743-47d5-87f7-4eeea8a9f288', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 5 x 70 mm, 200 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-5-x-70-mm-200-bucati/p/1058481', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058481_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '70.61 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 5 mm si  lungimea de 70 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 200 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '70', 'Diametru (mm)': '5', 'Diametru cap (mm)': '9.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': 'c884fdce-38b7-4ea7-8920-6f4cfd6fc9f8', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 5 x 80 mm, 200 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-5-x-80-mm-200-bucati/p/1058482', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058482_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '87.33 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 5 mm si  lungimea de 80 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 200 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '80', 'Diametru (mm)': '5', 'Diametru cap (mm)': '9.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '13b4d219-d291-4a36-8bc5-64c242da6711', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX20, autofiletant, din otel, zincat alb, 4 x 35/20 mm, 500 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx20-autofiletant-din-otel-zincat-alb-4-x-35/20-mm-500-bucati/p/1058464', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058464_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '63.88 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX20, diametrul de 4 mm si  lungimea de 35 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 500 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '35', 'Diametru (mm)': '4', 'Diametru cap (mm)': '7.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX20', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '94603ec6-f2bb-4d2a-9e26-02c0e1d6112f', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 4.5 x 70 mm, 200 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-4-5-x-70-mm-200-bucati/p/1058475', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058475_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '63.18 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 4.5 mm si  lungimea de 70 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 200 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '70', 'Diametru (mm)': '4.5', 'Diametru cap (mm)': '8.8', 'Inaltime cap (mm)': '2.8', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '0c08a9c6-65e1-4243-a6fa-c739416eba39', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX20, autofiletant, din otel, zincat alb, 4 x 40/25 mm, 500 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx20-autofiletant-din-otel-zincat-alb-4-x-40/25-mm-500-bucati/p/1058465', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058465.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '74.57 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX20, diametrul de 4 mm si  lungimea de 40 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 500 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '40', 'Diametru (mm)': '4', 'Diametru cap (mm)': '7.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX20', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': 'e9b30137-b14e-4f70-9a53-d230c196e0cc', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 5 x 100 mm, 100 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-5-x-100-mm-100-bucati/p/1058484', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058484_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '59.69 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 5 mm si  lungimea de 100 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 100 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '100', 'Diametru (mm)': '5', 'Diametru cap (mm)': '9.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '3271faba-c3dd-439d-a94a-4663debdd9ae', '_collection_name': 'dedeman-screws-collection4'}
{'title': 'Surub pentru tigla metalica, autoforant, Bilka, maro inchis RAL 8019, 4.8 x 70 mm, 100 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-tigla-metalica-autoforant-bilka-maro-inchis-ral-8019-4-8-x-70-mm-100-bucati/p/6040421', 'image': 'https://cdn.dedeman.ro/media/catalog/product/6/0/6040421_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '61.02 lei', 'description': 'Suruburile cu saiba de otel cu cauciuc se utilizeaza la fixarea metalului pe suport de lemn si asigura o perforare usoara si o prindere rezistenta.\nSuprafata galvanizata a suruburilor asigura protectie si rezistenta ridicata la intemperii, oferind si rezistenta la coroziune. Saiba din otel cu cauciuc asigura o etanseitate perfecta, nu permite apei sa patrunda prin gaura de perforare si reprezinta o dubla protectie impotriva coroziunii. Stratul de vopsea este rezistent la UV si asigura mentinerea culorii timp indelungat.\nUtilizarea acestui produs aduce dupa sine avantaje:\nstratul de protectie antirugina si protectia UV asigura rezistenta sporita in timpul instalarii si utilizarii;\ntratamentele aplicate in procesul de productie cresc rezistenta produsului la coroziune si permit mentinerea culorii in timp.\n  Suruburile sunt in numar de 250 in cutie, au culoarea maro inchis (RAL 8019), iar dimensiunile fiecaruia sunt 4.8 x 70 mm.', 'technical_specs': {'Brand': 'Bilka', 'Mod de ambalare': '100 bucati', 'Lungime (mm)': '70', 'Diametru (mm)': '4.8', 'Model': 'autoforant', 'Utilizare': 'fixare metal pe suport din lemn', 'Culoare': 'maro inchis RAL 8019', 'Finisaj': 'lucios', 'Diametru cap (mm)': '8', 'Capacitate perforare (mm)': '1.25', 'Alte caracteristici': 'strat de protectie antirugina; protectie UV'}, '_id': '35cdf696-2d86-46f5-9f78-4bef7728f940', '_collection_name': 'dedeman-screws-collection4'}
{'title': ' Surub pentru lemn, cu cap inecat, TX25, autofiletant, din otel, zincat alb, 5 x 50/27 mm, 250 bucati', 'link': 'https://www.dedeman.ro/ro/surub-pentru-lemn-cu-cap-inecat-tx25-autofiletant-din-otel-zincat-alb-5-x-50/27-mm-250-bucati/p/1058479', 'image': 'https://cdn.dedeman.ro/media/catalog/product/1/0/1058479_1.jpg?optimize=low&fit=bounds&height=266&width=266&canvas=266:266', 'price': '64.47 lei', 'description': 'Surubul este realizat din otel cu acoperire zincat alb, are amprenta TX25, diametrul de 5 mm si  lungimea de 50 mm.\nAcest produs are cap inecat si este filetat partial putand fi folosit la fixarea constructiilor din lemn.\nAceste suruburi se comercializeaza doar la cutii de 250 de bucati!', 'technical_specs': {'Brand': 'SEA', 'Material': 'otel', 'Tip cap': 'inecat', 'Lungime (mm)': '50', 'Diametru (mm)': '5', 'Diametru cap (mm)': '9.7', 'Inaltime cap (mm)': '3.1', 'Amprenta surub': 'TX25', 'Acoperire': 'zincat alb', 'Comercializare': 'cutie'}, '_id': '0cee3354-b78e-40ea-b769-0f6de2036b44', '_collection_name': 'dedeman-screws-collection4'}
"""